### ISSUE TITLE
关于client的析构

### ISSUE THREAD

**Issue by xchad** [IronsDu/gayrpc#16]
client有shared_ptr的 RpcTypeHandleManager 
RpcTypeHandleManager 又存有shared_ptr的client 和shared_ptr的service
这样client，service,RpcTypeHandleManager 不会析构不了吗
还是说就这样设计的，不需要析构

**Comment by IronsDu** [comment]
感谢提交issue。
前几天看到了，但由于忙工作没来得及回复。

确实，这里应该存在循环引用，应该添加depose相关处理。

**Comment by IronsDu** [comment]
@xchad Hello, I fix this issue.
