### ISSUE TITLE
echo示例运行问题

### ISSUE THREAD

**Issue by axun1992** [IronsDu/gayrpc#3]
请教一下，我在用vs2017运行echo示例，在客户端发送消息的request.set_message处报错，看起来是string释放时内存访问冲突。从网上查资料看我猜可能是开启了arena分配器，还没有进一步确认，请问这个问题作者有遇到么，是这个原因么？c++新手望指点，谢谢~

**Comment by IronsDu** [comment]
@yangxun983323204 我从来没遇到过呢；我自己开发时是用VS2019开发测试。不过GitHub的CI倒是用的VS 2017 https://github.com/IronsDu/gayrpc/blob/master/appveyor.yml#L9.

是否链接用的protobuf lib 和实际使用的dll不一致？

**Comment by axun1992** [comment]
找到原因了，是我在debug模式下运行，改成release没有这个情况了。

**Comment by IronsDu** [comment]
@yangxun983323204 欢迎提供一些建议。
