### ISSUE TITLE
服务与双向调用问题

### ISSUE THREAD

**Issue by axun1992** [IronsDu/gayrpc#4]
请问一条连接上可以安装多个服务吗，服务器如何调用已经连接的特定客户端上服务中的方法？

**Comment by IronsDu** [comment]
@yangxun983323204 

1.  `请问一条连接上可以安装多个服务吗`
一条链接上可以支持多个service。
我们可以在 https://github.com/IronsDu/gayrpc/blob/f16e4ff511580b5048270caf70fd85136874691b/examples/echo/pb/echo_service.proto#L23-L30 里定义多个service 即可。生成的代码里就会有多个Service Id（当然这里例子只是一个servic）：
https://github.com/IronsDu/gayrpc/blob/f16e4ff511580b5048270caf70fd85136874691b/examples/echo/pb/echo_service.gayrpc.h#L35-L39

2. `服务器如何调用已经连接的特定客户端上服务中的方法？`
（TCP)服务器可以直接创建一个到(TCP)客户端的RPC客户端，比如：
https://github.com/IronsDu/gayrpc/blob/f16e4ff511580b5048270caf70fd85136874691b/examples/echo/EchoServer.cpp#L22-L29
同理，（TCP)客户端可以在链接服务器成功之后创建一个RPC服务：
https://github.com/IronsDu/gayrpc/blob/f16e4ff511580b5048270caf70fd85136874691b/examples/echo/EchoClient.cpp#L71-L73

注：RPC核心其实与网络没有必然关系（也因此能做到上述目的）。

**Comment by IronsDu** [comment]
https://github.com/IronsDu/gayrpc/blob/f16e4ff511580b5048270caf70fd85136874691b/examples/echo/EchoClient.cpp#L71-L73

**Comment by axun1992** [comment]
感谢解答，有些明白了。不过一条TCP连接上支持多个Service的方法我还没搞懂，ServiceBuilder需要指定service类型，怎么支持多种service呢？

**Comment by IronsDu** [comment]
@yangxun983323204 
感谢指正！目前 ServiceBuilder 的接口遗漏了对多Service的支持！

https://github.com/IronsDu/gayrpc/blob/f16e4ff511580b5048270caf70fd85136874691b/src/gayrpc/utils/UtilsWrapper.h#L33-L64

按照上面封装代码的实现，如果我们不用ServiceBuilder，而是使用最基础/简单的接口，就可以使用多Service：只需要在链接进入时，构造不同的Service 来安装拦截器，然后RpcServiceType::Install(service)即可。

**Comment by IronsDu** [comment]
我或许应该让 serverCreator 作为一个数组来让ServiceBuilder提供多Service支持。

**Comment by axun1992** [comment]
明白了，继续学习~
